name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2

    - name: Use Node.js 12
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'

    - name: 🔨 Build Project
      run: |
        npm install
        npm run generate

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: hosting125544.a2fe2.netcup.net
        username: chat.jonasteichrueb.de
        password: ${{ secrets.password }}
        local-dir: ./dist/